coins_production:
  coin_generator_uid: ''
  storage_building_uid: ''
  storage_capacity_per_level:
    - amount: 1000
    - amount: 2000
    - amount: 3000
    - amount: 4000
    - amount: 5000

  coins_generation_per_level:
    - amount: 0.2
      harvest_capacity: 100

    - amount: 0.4
      harvest_capacity: 200

    - amount: 0.6
      harvest_capacity: 300

    - amount: 0.8
      harvest_capacity: 400

    - amount: 1.0
      harvest_capacity: 500

    - amount: 1.2
      harvest_capacity: 600